---
on:
    workflow_call:
      inputs:
        tag:
          type: string

jobs:
    list-open-prs:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4.2.2

            - name: Setup UV
              uses: astral-sh/setup-uv@v6

            - name: Set up Python

              run: uv python install

            - name: Install the project
              run: uv sync

            - name: Get Open PRs
              env:
                  GH_TOKEN: ${{ github.token }}
              run: |
                  gh pr list --json title,url,createdAt > "prs.json"

            - name: Alert Slack
              env:
                  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
                  REPO_NAME: ${{ github.event.repository.name }}"
              run: |
                  uv run scripts/list_open_prs.py
